# Generated by Django 5.0.6 on 2024-06-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='genero',
            field=models.CharField(choices=[('fem', 'Feminino'), ('mas', 'Masculino'), ('inf', 'Infantil'), ('sem', 'Sem Gênero')], max_length=3),
        ),
    ]
