# Generated by Django 5.0.6 on 2024-06-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_jogo',
            field=models.CharField(blank=True, choices=[('1', 'Jogo 1'), ('2', 'Jogo 2'), ('3', 'Jogo 3')], max_length=1, null=True),
        ),
    ]
