# Generated by Django 5.0.6 on 2024-06-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_tipo_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='numero_short',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
